# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='value',
            new_name='rating',
        ),
    ]
